### ISSUE TITLE
Failed to open new notebook after installation

### ISSUE THREAD

**Issue by SixtoSaez** [dotnet/interactive#1137]
### Describe the bug
Added this extension to VS Code after installing the .NET 5.0 SDK so I could try the new SQL notebook capability. After the install, tried to create a new notebook in both an existing folder and a new folder. It always fails with this error:

Unable to open 'Untitled-1.ipynb': Unable to get interactive launch options; .NET SDK must be installed first...

In trying to create a new notebook, the extension also attempts to install .NET Interactive again (see screenshot)

**Update:** seems the dotnet CLI thinks the extension is NOT installed (see second screenshot)

**Update2:** still cannot create a new notebook even after using the command line to install interactive (see third screenshot)
Maybe there is a mismatch in version installed be extension and the one actually installed.

The .NET SDK is installed as shown in the screenshot. I don't have any existing notebooks to test because this is the first time I have tried this extension.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
v1.0.215403

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ X] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![VSCode-new-notebook-bug](https://user-images.githubusercontent.com/1770667/110161302-2949f080-7dbb-11eb-9f7f-400a50177948.PNG)

![VSCode-new-notebook-CLI](https://user-images.githubusercontent.com/1770667/110162473-cce7d080-7dbc-11eb-9a71-7ca7b7cd4e98.PNG)

![VSCode-new-notebook-install-package](https://user-images.githubusercontent.com/1770667/110163156-b5f5ae00-7dbd-11eb-89fd-4434902b6c9f.PNG)

**Comment by brettfo** [comment]
@SixtoSaez Can you click on View -> Output then set the dropdown to ".NET Interactive : diagnostics"?  That window might give us some more information.

![image](https://user-images.githubusercontent.com/926281/110170591-4f699380-7daf-11eb-93ed-a3a84ac178c8.png)

**Comment by brettfo** [comment]
I just thought of something else.

In addition to the output window mentioned above, can you check one more place for errors?  Click Help -> Toggle Developer Tools then in the tool that opens, click the "Console" tab and take a screenshot of that whole thing?  It may give us some more information:

![image](https://user-images.githubusercontent.com/926281/110174571-2815c500-7db5-11eb-858e-06df31633950.png)

**Comment by SixtoSaez** [comment]
Sorry the delay, I was heads down on some other code.

Here are the results in the screenshot. Sorry for the small font but the debugger console tools text basically outputs the same errors as shown in the pop ups.


![VSCode-new-notebook-console-diagnostics](https://user-images.githubusercontent.com/1770667/110178547-9ae26880-7dd4-11eb-9358-2d8b0401c2c5.PNG)

**Comment by SixtoSaez** [comment]
I increased the font a little and expanded the error nodes. Hope this is more helpful.

![VSCode-new-notebook-debug-console](https://user-images.githubusercontent.com/1770667/110179129-8b175400-7dd5-11eb-8517-2715d1b6cef3.PNG)

**Comment by brettfo** [comment]
I'm willing to bet the VPN/corporate stuff might be the culprit.  Can you do an experiment for me?  I want to see which stage of tool acquisition is failing for you.

1. Create a temporary directory somewhere (desktop, etc., it doesn't really matter, I just don't want to write garbage files where you're doing your real work.)
2. Inside that directory, run the command that creates a new tool manifest file: `dotnet new tool-manifest`.  I'm hoping that a `.config` directory is created and `dotnet-tools.json` inside that directory.  The contents of the JSON should look something like this:
   ``` json
   {
     "version": 1,
     "isRoot": true,
     "tools": {}
   }
   ```
3. If that works, try the next command that actually acquires the tool: `dotnet tool install --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json --ignore-failed-sources Microsoft.dotnet-interactive --version 1.0.215401`
   Now I'm hoping that `dotnet-tools.json` looks like this:
   ``` json
   {
     "version": 1,
     "isRoot": true,
     "tools": {
       "microsoft.dotnet-interactive": {
         "version": "1.0.215401",
         "commands": [
           "dotnet-interactive"
         ]
       }
     }
   }
   ```

I'm hoping that one of those commands will fail with an error message that gives us a hint as to what might be happening.

Once you're done with that you can safely delete the `.config` directory and `dotnet-tools.json` without harming your system.

**Comment by SixtoSaez** [comment]
I did the test and the results are below. The first command worked and produced the expect results from your comments. The install command with the explicit version failed to find 1.0.215401 but it did find a newer version, 1.0.215503 and installed it. There weren't any error messages and it succeeded with warning NU1603 & the new version (see JSON result below).

I opened the same folder in VS Code and successfully create a new notebook. It showed at pop up with the message: installing notebook interactive 1.0.215401 and another that said the notebook was successfully create. My issue is resolved and I'll try the new functionality later this afternoon & report back here. Thanks for all the interest!!

PS C:\work\defects\vs-code-notebooks> dotnet --version
5.0.200

PS C:\work\defects\vs-code-notebooks> dotnet new tool-manifest
The template "Dotnet local tool manifest file" was created successfully.

PS C:\work\defects\vs-code-notebooks> dotnet tool install --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json --ignore-failed-sources Microsoft.dotnet-interactive --version 1.0.215401

C:\Program Files\dotnet\sdk\5.0.200\NuGet.targets(131,5): warning NU1801: Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json. 
[C:\Users\184561\AppData\Local\Temp\3kilhpdc.zmd\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.200\NuGet.targets(131,5): warning NU1801: Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json. [C:\Users\184561\AppData\Local\Temp\3kilhpdc.zmd\restore.csproj]
warning NU1603: restore depends on Microsoft.dotnet-interactive (>= 1.0.215401) but Microsoft.dotnet-interactive 1.0.215401 was not found. An approximate best match of Microsoft.dotnet-interactive 1.0.215503 was resolved.
You can invoke the tool from this directory using the following commands: 'dotnet tool run dotnet-interactive' or 'dotnet dotnet-interactive'.
Tool 'microsoft.dotnet-interactive' (version '1.0.215503') was successfully installed. Entry is added to the manifest file 

C:\work\defects\vs-code-notebooks\.config\dotnet-tools.json.

 Here is what the dotnet-tools.json contains after the install:

{
  "version": 1,
  "isRoot": true,
  "tools": {
    "microsoft.dotnet-interactive": {
      "version": "**1.0.215503**",
      "commands": [
        "dotnet-interactive"
      ]
    }
  }
}

**Comment by brettfo** [comment]
Thanks for running the experiment, I can safely confirm that the issue is the tool feed `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json` wasn't resolved from behind your company's firewall/VPN.  Version 1.0.215503  was later made available on NuGet.org as part of a completely unrelated process, and that's why it works currently, but as soon as we update the extension and tool again, you'll be back in this broken state.

I've filed issue #1146 to more concisely track the issue.

**Comment by brettfo** [comment]
I've also updated issue #1146 with a workaround, which is basically what we accidentally discovered here: force the tool version to be one that's available on NuGet.org so that when your machine can't access the specific tool URL, it can fall back to NuGet.org and still succeed.  This isn't the ideal workaround, but it'll at least unblock you while we come up with a better plan.
