### ISSUE TITLE
Unable to find appropriate .NET SDK when .NET Coding Pack and normal .NET SDK are both installed

### ISSUE THREAD

**Issue by dfinke** [dotnet/interactive#1355]
### Describe the bug
https://www.hanselman.com/blog/introducing-the-net-coding-pack-for-vs-code-getting-started-with-c-for-beginners 

I tried the above out, it includes .net interactive notebooks. Now when I try to create a new .net notebook (ipynb), I get the issues below. Both in vsc stable and insiders. 

I’m trying to figure out how to undo what the above install did. 

### Please complete the following:

**Which version of .NET Interactive are you using?**

1.0.210804+fc3dab56de568b6a43e77deeb79538af41d8f0c4

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [x] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/67258/119237544-5b8e0300-bb0b-11eb-857c-30a2c1314324.png)

**Comment by jonsequitur** [comment]
Does the .NET Interactive install ever complete? Also, any luck creating a notebook using .dib?

**Comment by dfinke** [comment]
I don't believe it completes. How can I tell? Trying a .dib, same issue.

**Comment by dfinke** [comment]
I'm wondering, and ideas on how to get back to a working state?

**Comment by jonsequitur** [comment]
You can often fix this by selecting `View: Reopen editor with` from the command palette and then `Jupyter Notebook`.

**Comment by dfinke** [comment]
That didn't work. Now I'm getting this error. This is using code insiders. I close and re-open vsc, still an issue.
This existing nb did work as I mentioned previously, even after installing the C# code pack. 

`Failed to set document metadata for 'file:///d%3A/test/mynb.ipynb': Error: Could not resolve external URI: http://localhost:54192/`

How/Should I clean my environment and reinstall code etc?

**Comment by jonsequitur** [comment]
Any better luck in non-Insiders VS Code?

**Comment by dfinke** [comment]
Same issue in stable. I can open and run the ipynb in Azure Data Studio

**Comment by brettfo** [comment]
This was a bit of a red herring and should be fixed by @colombod's #1358 and #1360.  Since those were just merged it'll be an hour or so before we have a full build that we can publish to the insiders channel.

**Comment by dfinke** [comment]
## More Info

Found this installed `.NET Education Bundle SDK Install Tool`. Only guessing it was installed by the C# pack.

https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-sdk

```log
Note: This is a very early preview of this tool and is not intended for use outside the .NET education bundle. 
Using this in other scenarios will result in broken installs on user machines due to conflict with the normal SDK installer.
```

Uninstalled in for vs code stable, notebooks work. For insiders, still have the issue:

```
Error: Could not resolve external URI ...
```

I'll try when the new build is published.

**Comment by jonsequitur** [comment]
I'll change the issue title to reflect this specific cause.

Generally, I'll also caution that we'll be a little unstable in Insiders, as the notebook APIs are changing there every few days and we can't always keep pace.

**Comment by dfinke** [comment]
Thank you! Resolved.
